# Generated by Django 5.2.1 on 2025-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Trader', 'Trader')], default='Buyer', max_length=20),
        ),
    ]
