# Generated by Django 5.2.1 on 2025-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trader',
            field=models.BooleanField(default=False),
        ),
    ]
